#!/usr/bin/env node
var fs = require('fs')
,	xml2js = require('xml2js')
,  parser = new xml2js.Parser()
,  input = process.argv[2] || null
,  output = process.argv[3] || null
,	exit = process.exit;
;

var usage = function(){
	console.log('')
	console.log('xml2json - converts xml to json (duh)');
	console.log('usage: xml2json input [output]');
	console.log('if output is not specified, it will be infered from input');
	console.log('')
}

if(!input){
	console.log('')
	console.log('you must specify at least input');
	console.log('use -h or --help for usage');
	console.log('');
	exit(1);
}else if(input == '-h' || input == '--help'){
	usage();
	exit(0);
}else{
	input = input[0] == '/' ? input : __dirname + '/' + input;

	output = output ? 
		output[0] == '/' ? output : __dirname + '/' + output
		:
		input.replace(/\.[^.]*$/,'.json');
}

console.log('');
console.log('reading from '+input);
var data = fs.readFileSync(input, 'utf8');

console.log('parsing...');
parser.parseString(data, function (err, result) {
	if(err){
		console.log(err);
		exit(1);
	}
	var result = JSON.stringify(result);
	fs.writeFileSync(output, result, 'utf8');
	console.log('wrote to '+output);
});

exit(0);